---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/authentication/login":
    post:
      summary: User login
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  refresh_token:
                    type: string
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/authentication/refresh":
    post:
      summary: Refresh JWT
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  refresh_token:
                    type: string
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
              required:
              - refresh_token
  "/authentication/change_password":
    patch:
      summary: Change user password
      tags:
      - Authentication
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: password changed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '401':
          description: current password incorrect
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '422':
          description: invalid new password
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                new_password:
                  type: string
              required:
              - current_password
              - new_password
  "/authentication/signup":
    post:
      summary: User sign up
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: successful signup
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  refresh_token:
                    type: string
        '422':
          description: invalid signup
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
              - email
              - password
              - password_confirmation
  "/redemptions":
    get:
      summary: List redemptions
      tags:
      - Redemptions
      security:
      - bearer_auth: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: integer
                  total_pages:
                    type: integer
                  total_count:
                    type: integer
                  redemptions:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        user_id:
                          type: integer
                        reward:
                          type: object
                          properties:
                            id:
                              type: integer
                            title:
                              type: string
                            description:
                              type: string
                            value_per_unit:
                              type: integer
                            quantity:
                              type: integer
                          required:
                          - id
                          - title
                          - description
                          - value_per_unit
                          - quantity
                        quantity:
                          type: integer
                        created_at:
                          type: string
                          format: date_time
                        updated_at:
                          type: string
                          format: date_time
                      required:
                      - id
                      - user_id
                      - reward
                      - quantity
                      - created_at
                      - updated_at
                required:
                - current_page
                - total_pages
                - total_count
                - redemptions
        '401':
          description: unauthorized
    post:
      summary: Create redemption
      tags:
      - Redemptions
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: not enough quantity
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reward_id:
                  type: integer
                quantity:
                  type: integer
              required:
              - reward_id
              - quantity
  "/redemptions/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Show redemption
      tags:
      - Redemptions
      security:
      - bearer_auth: []
      responses:
        '200':
          description: found
        '404':
          description: not found
        '403':
          description: forbidden
  "/rewards":
    get:
      summary: List rewards
      tags:
      - Rewards
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: integer
                  total_pages:
                    type: integer
                  total_count:
                    type: integer
                  rewards:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        title:
                          type: string
                        description:
                          type: string
                        value_per_unit:
                          type: integer
                        quantity:
                          type: integer
                      required:
                      - id
                      - title
                      - description
                      - value_per_unit
                      - quantity
                required:
                - current_page
                - total_pages
                - total_count
                - rewards
    post:
      summary: Create reward
      tags:
      - Rewards
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: created
        '403':
          description: forbidden
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                value_per_unit:
                  type: integer
                quantity:
                  type: integer
              required:
              - title
              - description
              - value_per_unit
              - quantity
  "/rewards/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Show reward
      tags:
      - Rewards
      responses:
        '200':
          description: found
        '404':
          description: not found
    put:
      summary: Update reward
      tags:
      - Rewards
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: updated
        '403':
          description: forbidden
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                value_per_unit:
                  type: integer
                quantity:
                  type: integer
    delete:
      summary: Delete reward
      tags:
      - Rewards
      security:
      - bearer_auth: []
      responses:
        '204':
          description: no content
        '403':
          description: forbidden
  "/users":
    get:
      summary: List users
      tags:
      - Users
      security:
      - bearer_auth: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  current_page:
                    type: integer
                  total_pages:
                    type: integer
                  total_count:
                    type: integer
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        email:
                          type: string
                        role:
                          type: integer
                        balance_points:
                          type: integer
                        created_at:
                          type: string
                          format: date_time
                        updated_at:
                          type: string
                          format: date_time
                      required:
                      - id
                      - email
                      - role
                      - balance_points
                      - created_at
                      - updated_at
                required:
                - current_page
                - total_pages
                - total_count
                - users
        '403':
          description: forbidden
    post:
      summary: Create user
      tags:
      - Users
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  role:
                    type: integer
                  balance_points:
                    type: integer
                  created_at:
                    type: string
                    format: date_time
                  updated_at:
                    type: string
                    format: date_time
                required:
                - id
                - email
                - role
                - balance_points
                - created_at
                - updated_at
        '403':
          description: forbidden
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
                role:
                  type: integer
                balance_points:
                  type: integer
              required:
              - email
              - password
              - password_confirmation
              - role
              - balance_points
  "/users/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Show user
      tags:
      - Users
      security:
      - bearer_auth: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  role:
                    type: integer
                  balance_points:
                    type: integer
                  created_at:
                    type: string
                    format: date_time
                  updated_at:
                    type: string
                    format: date_time
                required:
                - id
                - email
                - role
                - balance_points
                - created_at
                - updated_at
        '403':
          description: forbidden
    put:
      summary: Update user
      tags:
      - Users
      security:
      - bearer_auth: []
      parameters: []
      responses:
        '200':
          description: updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  email:
                    type: string
                  role:
                    type: integer
                  balance_points:
                    type: integer
                  created_at:
                    type: string
                    format: date_time
                  updated_at:
                    type: string
                    format: date_time
                required:
                - id
                - email
                - role
                - balance_points
                - created_at
                - updated_at
        '403':
          description: forbidden
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
                role:
                  type: integer
                balance_points:
                  type: integer
    delete:
      summary: Delete user
      tags:
      - Users
      security:
      - bearer_auth: []
      responses:
        '204':
          description: no content
        '403':
          description: forbidden
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
