import type { Metadata } from "next";
import Providers from "@/app/providers";
import "@/app/globals.css";
import NavBar from "./NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className="bg-background text-foreground min-h-screen">
        <Providers>
          <NavBar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
