/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */

export type GetRedemptions200RedemptionsItemReward = {
  id: number;
  title: string;
  description: string;
  value_per_unit: number;
  quantity: number;
};
