/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */
import type { GetRewards200RewardsItem } from './getRewards200RewardsItem';
import type { GetRewards200Pagination } from './getRewards200Pagination';

export type GetRewards200 = {
  rewards: GetRewards200RewardsItem[];
  pagination: GetRewards200Pagination;
};
