/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */

export type GetRewards200Pagination = {
  page: number;
  per_page: number;
  total: number;
  total_pages: number;
};
