/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */
import type { GetRedemptions200RedemptionsItem } from './getRedemptions200RedemptionsItem';

export type GetRedemptions200 = {
  current_page: number;
  total_pages: number;
  total_count: number;
  redemptions: GetRedemptions200RedemptionsItem[];
};
