/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */
import type { GetRedemptions200RedemptionsItem } from './getRedemptions200RedemptionsItem';
import type { GetRedemptions200Pagination } from './getRedemptions200Pagination';

export type GetRedemptions200 = {
  redemptions: GetRedemptions200RedemptionsItem[];
  pagination: GetRedemptions200Pagination;
};
