/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */
import type { GetUsers200UsersItem } from './getUsers200UsersItem';

export type GetUsers200 = {
  current_page: number;
  total_pages: number;
  total_count: number;
  users: GetUsers200UsersItem[];
};
