/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */

export type PostUsers201 = {
  id?: number;
  email?: string;
  role?: number;
  balance_points?: number;
};
