/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */

export type PostRedemptions200 = {
  id?: number;
  user_id?: number;
  reward_id?: number;
  quantity?: number;
};
