/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */

export type PostUsersBodyUser = {
  email: string;
  password: string;
  password_confirmation: string;
  role: number;
  balance_points: number;
};
