/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * API V1
 * OpenAPI spec version: v1
 */
import type { PostUsersBodyUser } from './postUsersBodyUser';

export type PostUsersBody = {
  user: PostUsersBodyUser;
};
